---
- name: "make sure python is installed"
  raw: "test -e /usr/bin/python && /usr/bin/pacman -Syy && /usr/bin/pacman -S --noconfirm python"
  changed_when: false
  ignore_errors: true

- name: include the pacman setup
  include: pacman.yml

- name: install packages
  community.general.pacman:
    name: "{{ wsbase_package_list }}"
    state: present
  notify: "{{ wsbase_post_install_notfiers }}"
