---
- name: "check for python"
  raw: "test -e /usr/bin/python || /usr/bin/pacman -Sy --noconfirm python"
  changed_when: false

- name: include the pacman setup
  include: pacman.yml

- name: install packages
  community.general.pacman:
    name: "{{ wsbase_package_list + wsbase_additional_packages }}"
    state: present
  notify: "{{ wsbase_post_install_notfiers }}"

- name: install any pip packages
  pip:
    name: "{{ wsbase_pip_packages }}"
