- name: download pacman mirror list
  get_url:
    url: "{{ wsbase_pacman_mirror_list_url }}"
    dest: "/etc/pacman.d/mirrorlist"
    force: true
  tags:
    - molecule-idempotence-notest

- name: "uncomment `#Server` in pacman mirror list"
  replace:
    dest: "/etc/pacman.d/mirrorlist"
    regexp: '^#Server'
    replace: 'Server'
  tags:
    - molecule-idempotence-notest

- name: Synchronise the package databases
  command: /usr/bin/pacman -Syy # noqa 301
  tags:
    - molecule-idempotence-notest

- name: debug
  debug:
    var: wsbase_pacman_key_servers

- name: Refresh the pacman-keys {{ keyserver }} # noqa 301
  command: "/usr/bin/pacman-key --refresh-keys --keyserver {{ keyserver.split(' ')[3] }}"
  retries: "{{ wsbase_pacman_key_refresh_retries }}"
  delay: "{{ wsbase_pacman_key_refresh_delay }}"
  with_random_choice: "{{ wsbase_pacman_key_servers }}"
  register: keyrefresh
  until: keyrefresh.rc == 0
  loop_control:
    loop_var: keyserver
  tags:
    - molecule-idempotence-notest

- name: "uncomment colors"
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    regexp: "^Color"
    insertafter: "^#Color"
    line: "Color"
