# If you tag your "include_role" and there is more than one, you can skip specific roles with:
# $ ANSIBLE_SKIP_TAGS="geerlingguy.nginx,geerlingguy.php" molecule converge
---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:

    - name: set the key server lookup if its not set
      set_fact:
        wsbase_pacman_key_servers: "{{ lookup('community.general.dig', '_pgpkey-http._tcp.eu.pool.sks-keyservers.net', 'qtype=SRV', wantlist=True) }}"
      when:
        - wsbase_pacman_key_servers is not defined
        - not lookup('env','GH_IN_ACTIONS') | default(false, true) | bool

    - name: "Include the role you are developing here"
      include_role:
        apply:
          become: true
        name: "ansible-role-ws-base"
