---
# A place to prep your container / vm for something your role will rely on but not actually do. You might consider baking it into your container / vm image if its not sensitive
- hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: "check for python"
      raw: "test -e /usr/bin/python || /usr/bin/pacman -Sy --noconfirm python python-pip"
      changed_when: false

    - name: update everything
      command: /usr/bin/pacman -Syu --noconfirm

    - name: install some things which arent in the container but are in the tar image
      raw: /usr/bin/pacman -S --noconfirm vim base-devel

    - name: include the role defaults
      include_vars:
        dir: ../../defaults/
        extensions:
          - yml

    - name: "Include the user role"
      include_role:
        apply:
          become: true
        name: "{{ preprole }}"
      loop_control:
        loop_var: preprole
      loop:
        - "grog.user"
        - "grog.authorized-key"

- import_playbook: "../../getkeyservers.yml"
