- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: remove the keyservers yml
      file:
        path: ./molecule/docker/group_vars/arch/zz_meta_keyservers.yml
        state: absent
