---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    force: ${MOL_DEP_RESOLVE:-true}
driver:
  name: docker
  # Dont resolve dependencies unless you have to
platforms:
  - name: "geosword-base"
    image: archlinux:20200908
    dockerfile: Dockerfile.j2
    pull: false
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
# privileged to get systemd working
    privileged: true
# pre_build_image: true means PULL from docker hub
    pre_build_image: ${MOL_DEP_BUILD_IMAGE:-true}
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
# edit .yamllint to change linting settings
lint: |
  set -e
  yamllint .
  ansible-lint -c .ansible-lint meta/*.yml tasks/*.yml vars/main.yml handlers/*.yml
