---
# A place to prep your container / vm for something your role will rely on but not actually do. You might consider baking it into your container / vm image if its not sensitive
- hosts: all
  gather_facts: false
  tasks:
    - name: "check for python"
      raw: "test -e /usr/bin/python || /usr/bin/pacman -Sy --noconfirm python"
      changed_when: false

    - name: install some things which arent in the container but are in the tar image
      raw: /usr/bin/pacman -S --noconfirm vim base-devel

    - name: debug arch lookup
      command: dig _pgpkey-http._tcp.eu.pool.sks-keyservers.net SRV
      no_log: false

    - name: debug google lookup
      command: dig www.google.com
      no_log: false
