# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: check out the codebase
        uses: actions/checkout@v2

      - name: set name resolution to something else
        run: sudo sh -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'

      - name: Check the resolution is actually working via dig
        run: dig +noall +answer srv _pgpkey-http._tcp.eu.pool.sks-keyservers.net

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip3 install -r requirements.txt

      # - name: output the arch key servers to a variable file because... lookups in molecule in gh actions
        # run: ansible-playbook getkeyservers.yml

      - name: Show that the var file actually exists and has content in it
        run: cat ./molecule/docker/group_vars/arch/zz_meta_keyservers.yml

      - name: Run molecule tests
        run: molecule test --scenario-name docker
